Vagrant.configure("2") do |config|

#whicle vagrant up processing it might ask to select network > select realtech wireless LAN
#Manage Jenkins / Global Tool Configuration and set Path to Git executable(not required)
  config.vm.define "slave" do |slave|
    slave.vm.box = "ubuntu/bionic64"
	slave.vm.network "private_network", ip: "192.168.40.21"
	slave.vm.network "public_network", bridge: "Realtek 8821CE Wireless LAN 802.11ac PCI-E NIC"
	slave.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	 vb.cpus = 2
   end
   slave.vm.provision "shell", inline: <<-SHELL
     echo "hello slave"
   SHELL
  end
  
 end
